[build]
target = "avr-specs/avr-atmega328p.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]


[env]
ARDUINO_SDK_CONFIG = { value = "custom.yaml", relative = true, force = true }